# Generated by Django 5.1.7 on 2025-04-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='description',
        ),
    ]
