# Generated by Django 5.1.7 on 2025-04-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_restaurant_rating_restaurant_seats_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reservation_time', models.TextField(max_length=100)),
                ('number_of_people', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('special_requests', models.TextField(max_length=200)),
            ],
        ),
    ]
