# Generated by Django 5.1.7 on 2025-04-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_reservation_name_reservation_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed')], default=0),
        ),
    ]
