# Generated by Django 5.1.7 on 2025-04-11 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
