# Generated by Django 5.1.7 on 2025-04-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_restaurant_user_alter_user_chosen_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
