# Generated by Django 5.1.7 on 2025-04-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('owner', 'Owner')], default='normal', max_length=10),
        ),
    ]
