# Generated by Django 5.1.7 on 2025-04-18 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.cuisine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='allergy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.allergy'),
            preserve_default=False,
        ),
    ]
