# Generated by Django 5.1.7 on 2025-04-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
