# Generated by Django 5.1.7 on 2025-04-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='description',
            new_name='allergies',
        ),
    ]
