# Generated by Django 5.1.7 on 2025-04-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_allergy_remove_restaurant_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='allergy',
            field=models.TextField(max_length=100),
        ),
    ]
