# Generated by Django 5.1.7 on 2025-04-18 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_allergy_chosenallergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.cuisine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='allergies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.allergy'),
        ),
    ]
