# Generated by Django 5.1.7 on 2025-04-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_restaurant_cuisines_alter_restaurant_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chosen_allergy',
            field=models.ManyToManyField(through='api.ChosenAllergy', to='api.allergy'),
        ),
    ]
