# Generated by Django 5.1.7 on 2025-04-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_restaurant_allergy_remove_restaurant_cuisine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='allergy',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
