# Generated by Django 5.1.7 on 2025-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_restaurant_allergy_remove_restaurant_cuisine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='allergy',
            field=models.ManyToManyField(related_name='restaurants', to='api.allergy'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.ManyToManyField(related_name='restaurants', to='api.cuisine'),
        ),
    ]
