# Generated by Django 5.1.7 on 2025-04-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_restaurant_allergy_remove_restaurant_cuisine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='allergy',
        ),
    ]
