# Generated by Django 5.1.7 on 2025-04-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_restaurant_allergy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
    ]
