# Generated by Django 5.1.7 on 2025-04-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_restaurant_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.ManyToManyField(related_name='restaurants', to='api.cuisine'),
        ),
    ]
