# Generated by Django 5.1.7 on 2025-04-20 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_restaurant_allergy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='allergy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.allergy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.cuisine'),
            preserve_default=False,
        ),
    ]
