# Generated by Django 5.1.7 on 2025-04-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_restaurant_allergy_remove_restaurant_cuisine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='allergy',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='allergys',
            field=models.ManyToManyField(to='api.allergy'),
        ),
    ]
