# Generated by Django 5.1.7 on 2025-04-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_restaurant_allergy_restaurant_allergys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergys',
            field=models.ManyToManyField(related_name='allergy', to='api.allergy'),
        ),
        migrations.AddField(
            model_name='user',
            name='cuisines',
            field=models.ManyToManyField(related_name='cuisine', to='api.cuisine'),
        ),
    ]
