# Generated by Django 5.1.7 on 2025-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_allergys_user_cuisines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergys',
            field=models.ManyToManyField(related_name='allergys', to='api.allergy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cuisines',
            field=models.ManyToManyField(related_name='cuisines', to='api.cuisine'),
        ),
    ]
