# Generated by Django 5.1.7 on 2025-04-21 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_user_allergys_alter_user_cuisines'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='chosenAllergy', max_length=100)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.allergy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='chosen_allergy',
            field=models.ManyToManyField(through='api.ChosenAllergy', to='api.allergy'),
        ),
    ]
