# Generated by Django 5.1.7 on 2025-04-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_review_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='Restaurant',
        ),
    ]
