# Generated by Django 5.1.7 on 2025-04-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_name_review_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
