# Generated by Django 5.1.7 on 2025-04-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_review_ambience_rating_review_food_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='created_at',
        ),
    ]
