# Generated by Django 5.1.7 on 2025-04-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_wishlist_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='notes',
        ),
    ]
