# Generated by Django 5.1.7 on 2025-04-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_wishlistitem_owner_alter_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='owner',
            new_name='user',
        ),
    ]
