# Generated by Django 5.1.7 on 2025-04-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_owner_wishlistitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='user',
            new_name='owner',
        ),
    ]
