# Generated by Django 5.1.7 on 2025-04-23 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_user_wishlistitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_wishlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
