# Generated by Django 5.1.7 on 2025-04-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_wishlistshare_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='shared_with',
        ),
    ]
