# Generated by Django 5.1.7 on 2025-04-23 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_wishlistitem_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlistshare',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared', to='api.wishlist'),
        ),
    ]
