# Generated by Django 5.1.7 on 2025-04-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_wishlist_shared_with_alter_wishlistshare_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Declined')], default=0),
        ),
    ]
