# Generated by Django 5.1.7 on 2025-04-28 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosencuisine',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_by', to='api.cuisine'),
        ),
        migrations.AlterField(
            model_name='chosencuisine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_cuisines', to=settings.AUTH_USER_MODEL),
        ),
    ]
